# time -> 运行时间，单位秒
# online -> 当前在线人数
# flow -> 历史进入退出人数
# tps -> 服务器运行状况
# memory -> 服务器内存使用，取值0-1.0
control:
  expr: '(time > 36000 && online < 1) || tps < 5'
wait: 15
force: false
kick:
  to:
  - 'Lobby'
message:
  notify: '&1为了服务器流畅，本大厅即将重启！请玩家前往其他大厅或等待自动传送至主大厅！'
debug: false