control:
  expr: "(${time} > 36000 && ${online} < 1)"
# Wait for server bootstrapped in seconds and start TPS tracker.
wait: 15
force: false
force_wait: 120
kick_to:
  - "lobby-1"
schedule:
- "at 12:30 say 大家中午好"
- "every 18:00 say 大家下午好"
message:
  notify: "&1为了服务器流畅，本大厅即将重启！请玩家前往其他大厅或等待自动传送至主大厅！"
valid_sqlite: true
valid_server_alive: true
extension:
  auto_dump: true
  limit_interact_rate: true
