control:
  expr: "(${time} > 36000 && ${online} < 1)"
  enable: false
# Wait for server bootstrapped in seconds and start TPS tracker.
wait: 30
force_wait: 300
kick_to:
  - "lobby"
schedule:
  - "at 12:30 say 大家中午好"
  - "every 18:00 say 大家下午好"
message:
  notify: "&1为了服务器流畅，本大厅即将重启！请玩家前往其他大厅或等待自动传送至主大厅！"
valid_sqlite: false
valid_server_alive: true
extension:
  auto_dump: false
  advance_tiles_mechanism: false
  kick_fallback: false
bootstrap_watchdog: 600
stop_command: stop
commands_alt_checker:
  - "help"
  - "plugins"
  - "version"
traffic_rules:
  - action: LOG
